import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  offJtSidebar: [{ type: 'autogenerated', dirName: 'off-jt' }],
  devSidebar: [{ type: 'autogenerated', dirName: 'dev' }],
  bulletinSidebar: [{ type: 'autogenerated', dirName: 'bulletin' }],
};

export default sidebars;
